from src.chatbot.constants import ConversationState, FoodOrderState

_ALL_STATES = set(ConversationState)
_ALL_FOOD_STATES = set(FoodOrderState)

VALID_TRANSITIONS: dict[ConversationState | None, set[ConversationState]] = {
    None: _ALL_STATES,
    ConversationState.GREETING: {
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.FAREWELL,
        ConversationState.PICKUP_PING,
    },
    ConversationState.FAREWELL: {
        ConversationState.GREETING,
        ConversationState.MISC,
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.PICKUP_PING,
        ConversationState.ORDER_COMPLETE,
    },
    ConversationState.FOOD_ORDER: {
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.PICKUP_PING,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.ORDER_COMPLETE,
    },
    ConversationState.ADDING_MODIFIERS: {
        ConversationState.ADDING_MODIFIERS,
        ConversationState.FOOD_ORDER,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.PICKUP_PING,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.ORDER_COMPLETE,
    },
    ConversationState.MENU_QUESTION: {
        ConversationState.MENU_QUESTION,
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.PICKUP_PING,
    },
    ConversationState.RESTAURANT_QUESTION: {
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.MENU_QUESTION,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.PICKUP_PING,
    },
    ConversationState.PICKUP_PING: {
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.PICKUP_PING,
        ConversationState.FAREWELL,
        ConversationState.MISC,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.ORDER_COMPLETE,
    },
    ConversationState.VAGUE_MESSAGE: _ALL_STATES - {ConversationState.GREETING},
    ConversationState.MISC: _ALL_STATES - {ConversationState.GREETING},
    ConversationState.ORDER_COMPLETE: {
        ConversationState.GREETING,
        ConversationState.FOOD_ORDER,
        ConversationState.ADDING_MODIFIERS,
        ConversationState.FAREWELL,
        ConversationState.MISC,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.MENU_QUESTION,
        ConversationState.PICKUP_PING,
    },
}

VALID_FOOD_ORDER_TRANSITIONS: dict[FoodOrderState | None, set[FoodOrderState]] = {
    None: _ALL_FOOD_STATES,
    FoodOrderState.NEW_ORDER: _ALL_FOOD_STATES,
    FoodOrderState.ADD_TO_ORDER: _ALL_FOOD_STATES,
    FoodOrderState.MODIFY_ORDER: _ALL_FOOD_STATES,
    FoodOrderState.REMOVE_FROM_ORDER: _ALL_FOOD_STATES,
    FoodOrderState.SWAP_ITEM: _ALL_FOOD_STATES,
    FoodOrderState.CANCEL_ORDER: {FoodOrderState.NEW_ORDER},
    FoodOrderState.ADDING_MODIFIERS: _ALL_FOOD_STATES,
    FoodOrderState.REVIEW_ORDER: _ALL_FOOD_STATES,
}
