from src.chatbot.constants import ConversationState

_ALL_STATES = set(ConversationState)

VALID_TRANSITIONS: dict[ConversationState | None, set[ConversationState]] = {
    None: _ALL_STATES,
    ConversationState.GREETING: {
        ConversationState.FOOD_ORDER,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.FAREWELL,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.FAREWELL: {
        ConversationState.GREETING,
        ConversationState.MISC,
        ConversationState.FOOD_ORDER,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.ORDER_COMPLETE,
    },
    ConversationState.FOOD_ORDER: {
        ConversationState.FOOD_ORDER,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.ORDER_COMPLETE,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.MENU_QUESTION: {
        ConversationState.MENU_QUESTION,
        ConversationState.FOOD_ORDER,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.RESTAURANT_QUESTION: {
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.FOOD_ORDER,
        ConversationState.MENU_QUESTION,
        ConversationState.FAREWELL,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MISC,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.PICKUP_PING: {
        ConversationState.FOOD_ORDER,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.FAREWELL,
        ConversationState.MISC,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.ORDER_COMPLETE,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.PICKUP_TIME_SUGGESTION: {
        ConversationState.FOOD_ORDER,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.FAREWELL,
        ConversationState.MISC,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.MENU_QUESTION,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.ORDER_COMPLETE,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.VAGUE_MESSAGE: _ALL_STATES - {ConversationState.GREETING},
    ConversationState.MISC: _ALL_STATES - {ConversationState.GREETING},
    ConversationState.ORDER_COMPLETE: {
        ConversationState.GREETING,
        ConversationState.FOOD_ORDER,
        ConversationState.FAREWELL,
        ConversationState.MISC,
        ConversationState.VAGUE_MESSAGE,
        ConversationState.RESTAURANT_QUESTION,
        ConversationState.MENU_QUESTION,
        ConversationState.PICKUP_PING,
        ConversationState.PICKUP_TIME_SUGGESTION,
        ConversationState.ORDER_REVIEW,
    },
    ConversationState.ORDER_REVIEW: _ALL_STATES - {ConversationState.GREETING},
}
