from src.chatbot.features.ordering.prompts import (
    EXTRACT_ADD_ITEMS_SYSTEM_PROMPT,
    EXTRACT_MODIFY_ITEMS_SYSTEM_PROMPT,
    EXTRACT_ORDER_ITEMS_SYSTEM_PROMPT,
    EXTRACT_PENDING_MOD_SELECTIONS_SYSTEM_PROMPT,
    EXTRACT_SWAP_ITEMS_SYSTEM_PROMPT,
    RESOLVE_CONFIRMATION_SYSTEM_PROMPT,
    RESOLVE_REMOVE_ITEM_SYSTEM_PROMPT,
)

__all__ = [
    "EXTRACT_ADD_ITEMS_SYSTEM_PROMPT",
    "EXTRACT_MODIFY_ITEMS_SYSTEM_PROMPT",
    "EXTRACT_ORDER_ITEMS_SYSTEM_PROMPT",
    "EXTRACT_PENDING_MOD_SELECTIONS_SYSTEM_PROMPT",
    "EXTRACT_SWAP_ITEMS_SYSTEM_PROMPT",
    "RESOLVE_CONFIRMATION_SYSTEM_PROMPT",
    "RESOLVE_REMOVE_ITEM_SYSTEM_PROMPT",
]
